### ISSUE TITLE
単一実行ファイルのインストール

### ISSUE THREAD

**Issue by GrudgeDuck** [takemal-studio/mkProjfolder#10]
#9 で`Linux`では単一実行ファイルをインストールできるようになったが、最終的には異なるプラットフォームでも同じ方法で、より簡単にインストールできるようにしたい。デファクトスタンダードが何かはよくわからないが、[これ](https://qiita.com/abcsupergt/items/08a1c2df03a5d4c10539)とかが参考になるかもしれない。

他の方法も模索しつつ、インストールと使用方法の簡略化をする必要があるかと。

**Comment by takemal-studio** [comment]
#12 #13
