### ISSUE TITLE
READMEへの追加事項

### ISSUE THREAD

**Issue by echoSayonara** [takemal-studio/mkProjfolder#2]
以下の2つを追加して欲しい。

# Installation
どのようにインストールするか (`pip`経由か`git clone`なのかなど)
もしOSなどによってインストール方法が異なるなら、主要なOS(Windows, Mac, Ubuntuなど)については書いてあげると優しい。
ちなみに`Ubuntu 18.04`と`python3.6`では`git clone`だけで問題なく動いた。

## 例

Install dependencies (if needed).
```
pip install pandas networks
```

Run following scripts to install mkproj.
```
git clone https://github.com/takemal-studio/mkProjfolder && cd mkProjfolder
```

----
# Dependencies
+ サポートされているPythonのバージョン
+ 依存パッケージとそのバージョン
  
## 例
+ `python` (`v.3.x` or later)
+ `pandas` (`v.x.x`)
+ `networkx` (`v.x.x`)

**Comment by takemal-studio** [comment]
少し改善しました．
足りないところはこれから追加していきます．
